//{{NO_DEPENDENCIES}}
// Archivo de inclusión generado de Microsoft Visual C++.
// Usado por 1985194GonzalezCastilleroJoseMiguelEDDProyecto.rc
//
#define IDD_LOGIN                       101
#define IDR_MENU1                       103
#define IDD_REGUSER                     104
#define IDD_REGCARNET                   106
#define IDD_REGPERSONA                  108
#define IDD_REGVACUNA                   110
#define IDD_MODCAR                      112
#define IDD_DELCAR                      114
#define IDD_BUSCAR                      116
#define IDD_BUSCAR2                     118
#define IDC_LOGIN                       1001
#define IDC_BUTTON2                     1002
#define IDC_REGISTER                    1003
#define IDC_USERKEY                     1004
#define IDC_PASSWORD                    1005
#define IDC_APATERNR                    1008
#define IDC_AMATERNR                    1009
#define IDC_NOMBRE                      1010
#define IDC_NOMBRER                     1011
#define IDC_USERKER                     1012
#define IDC_PASSWORR                    1013
#define IDC_APATERNP                    1014
#define IDC_AMATERNP                    1015
#define IDC_NOMBREP                     1016
#define IDC_CURPP                       1017
#define IDC_DATETIMEPICKERP             1018
#define IDC_RFCP                        1019
#define IDC_CALLP                       1020
#define IDC_COLONIP                     1021
#define IDC_CITYP                       1022
#define IDC_ESTADP                      1023
#define IDC_ESTACIVIP                   1024
#define IDC_TELEFP                      1025
#define IDC_IDENTIFP1                   1026
#define IDC_SEXP                        1027
#define IDC_GRUOCUP                     1028
#define IDC_PERRIEP                     1029
#define IDC_IDENTIFP2                   1030
#define IDCANCEP                        1031
#define IDOP                            1032
#define IDC_IDENTIFP3                   1033
#define IDC_TIPOVAC                     1034
#define IDC_MARCAVAC                    1035
#define IDC_NOMDOS                      1036
#define IDC_CLAVAC                      1037
#define IDC_DESCVAC                     1038
#define IDC_PREVAC                      1039
#define IDOV                            1040
#define IDCANCEV                        1041
#define IDC_CURPAT                      1042
#define IDC_VACMARC                     1043
#define IDC_RNOMDOS                     1044
#define IDC_RFECDOS                     1045
#define IDC_RLOT                        1046
#define IDC_RCENTVAC                    1047
#define IDC_BCURPAT                     1048
#define IDC_BBUSCAR                     1049
#define IDC_BBUSCAR2                    1049
#define IDC_BUCURPAT                    1050
#define IDC_BMARVAC                     1051
#define IDC_BUMARVAC                    1051
#define IDC_BNUMDOS                     1052
#define IDC_BUNUMDOS                    1052
#define IDC_BLOTE                       1053
#define IDC_BULOTE                      1053
#define IDC_BFECVAC                     1054
#define IDC_EDIT6                       1055
#define IDC_BLOT                        1055
#define IDC_B2BLOTE                     1055
#define IDC_BCENVAC                     1056
#define IDC_BUCENVAC                    1056
#define IDC_ECURPAT                     1057
#define IDC_EDCURPAT                    1058
#define IDC_EMARVAC                     1059
#define IDC_ENUMDOS                     1060
#define IDC_EFECDOS                     1061
#define IDC_ELOTE                       1062
#define IDC_ECENVAC                     1063
#define IDC_MCURPAT                     1064
#define IDC_MBUSCAR                     1065
#define IDC_EBUSCAR                     1066
#define IDC_MOCURPAT                    1067
#define IDC_MMARVAC                     1068
#define IDC_MNUMDOS                     1069
#define IDC_MFECDOS                     1070
#define IDC_MLOTE                       1071
#define IDC_MCENVAC                     1072
#define IDOB                            1073
#define IDOD                            1075
#define IDCANCED                        1076
#define IDOM                            1077
#define IDCANCEM                        1078
#define IDORC                           1079
#define IDCANCERC                       1080
#define IDOU                            1081
#define IDCANCEU                        1082
#define IDC_B2BUNUMCAR                  1083
#define IDC_B2BUCURPAT                  1084
#define IDC_B2BULOTE                    1088
#define IDC_B2NUMCAR                    1090
#define IDC_B2BUSCAR                    1091
#define IDC_NUMCAR                      1092
#define IDC_ENUMCAR                     1093
#define IDC_MNUMCAR                     1094
#define IDC_B2BUCENVAC                  1095
#define IDC_BUNUMCAR                    1096
#define IDC_BUFECDOS                    1097
#define IDC_BNUMCAR                     1098
#define IDC_B2BUFECDOS                  1099
#define IDC_B2BUNUMDOS                  1100
#define IDC_B2BUMARVAC                  1101
#define IDC_BNUMCA                      1102
#define IDC_BCURPPAT                    1103
#define IDC_BVACUNA                     1104
#define IDC_BDOSIS                      1105
#define IDC_EDIT5                       1106
#define IDC_BVACCEN                     1107
#define IDOB2                           1108
#define IDC_B2BNUMCAR                   1109
#define IDC_B2BCURPAT                   1110
#define IDC_B2BMARVAC                   1111
#define IDC_B2BNUMDOS                   1112
#define IDC_EDIT7                       1113
#define IDC_B2BCENVAC                   1113
#define IDC_B2BFECDOS                   1114
#define ID_CARNET_REGISTRARCARNET       40001
#define ID_CARNET_ELIMINARCARNET        40002
#define ID_CARNET_MODIFICARCARNET       40003
#define ID_CARNET_LISTADODECARNET       40004
#define ID_CARNET_BUSCARCARNET          40005
#define ID_VACUNA_AGREGARVACUNA         40006
#define ID_PERSONA_REGISTRARPERSONA     40007
#define ID_ACERCADE_MANUALDEUSUARIO     40008
#define ID_ACERCADE_SALIR               40009
#define ID_CARNET_MODIFICARCARNET40010  40010
#define ID_CARNET_ELIMINARCARNET40011   40011
#define ID_CARNET_BUSCARCARNET40012     40012
#define ID_PERSONA_BUSCARPORNUMERODECARNET 40013
#define ID_PERSONA_BUSCARPORNOMBREDEPERSONA 40014
#define ID_CARNET_BUSCARPORNUMERODECARNET 40015
#define ID_CARNET_BUSCARPORNOMBREDEPERSONA 40016

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        120
#define _APS_NEXT_COMMAND_VALUE         40017
#define _APS_NEXT_CONTROL_VALUE         1115
#define _APS_NEXT_SYMED_VALUE           102
#endif
#endif
